name: CI - Run API tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start server (background) and wait for health
        run: |
          npm start &                     # start server in background
          for i in {1..15}; do
            curl -sSf http://localhost:10000/health && break
            sleep 1
          done

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run tests/postman_collection.json -e tests/postman_env.json --env-var "base_url=http://localhost:10000"
